<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CalleeService2"
             targetNamespace="http://api.ws.transactions.lkp.lanit.ru/"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:wsp="http://www.w3.org/ns/ws-policy"
             xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:tns="http://api.ws.transactions.lkp.lanit.ru/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://api.ws.transactions.lkp.lanit.ru/" schemaLocation="CalleeService2_schema1.xsd"/>
        </xsd:schema>
    </types>
    <message name="doSomethingResponse">
        <part name="parameters" element="tns:doSomethingResponse">
        </part>
    </message>
    <message name="doSomething">
        <part name="parameters" element="tns:doSomething">
        </part>
    </message>
    <portType name="CalleeService">
        <operation name="doSomething">
            <input message="tns:doSomething">
            </input>
            <output message="tns:doSomethingResponse">
            </output>
        </operation>
    </portType>
    <binding name="CalleeBeanImplPortBinding" type="tns:CalleeService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="doSomething">
            <soap:operation soapAction=""/>
            <wsp:PolicyReference URI="#278ad583-8800-4b3d-80a7-511cd6abddd5"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="CalleeService2">
        <port name="CalleeBeanImplPort" binding="tns:CalleeBeanImplPortBinding">
            <soap:address location="http://localhost:9082/callee/CalleeService2"/>
        </port>
    </service>
    <wsp:Policy wsu:Id="278ad583-8800-4b3d-80a7-511cd6abddd5"><wsp:ExactlyOne><wsp:All><wspns0:ATAssertion xmlns:wspns0="http://schemas.xmlsoap.org/ws/2004/10/wsat"/></wsp:All><wsp:All><ns2:ATAssertion xmlns:ns2="http://docs.oasis-open.org/ws-tx/wsat/2006/06"/></wsp:All></wsp:ExactlyOne></wsp:Policy>
</definitions>
