<?xml version="1.0" encoding="UTF-8"?>
<definitions name="CallerService2"
             targetNamespace="http://api.ws.transactions.lkp.lanit.ru/"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:wsp="http://www.w3.org/ns/ws-policy"
             xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:tns="http://api.ws.transactions.lkp.lanit.ru/"
             xmlns:wsat10="http://schemas.xmlsoap.org/ws/2004/10/wsat"
             xmlns:wsat11="http://docs.oasis­open.org/ws­tx/wsat/2006/06"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsp:Policy wsu:Id="ATPolicy">
        <wsp:ExactlyOne>
            <wsat11:ATAssertion />
            <wsat10:ATAssertion />
        </wsp:ExactlyOne/>
    </wsp:Policy>
    <types>
        <xsd:schema>
            <xsd:import namespace="http://api.ws.transactions.lkp.lanit.ru/" schemaLocation="CallerService2_schema1.xsd"/>
        </xsd:schema>
    </types>
    <message name="doSomethingResponse">
        <part name="parameters" element="tns:doSomethingResponse">
        </part>
    </message>
    <message name="doSomething">
        <part name="parameters" element="tns:doSomething">
        </part>
    </message>
    <portType name="CallerService">
        <operation name="doSomething">
            <input message="tns:doSomething">
            </input>
            <output message="tns:doSomethingResponse">
            </output>
        </operation>
    </portType>
    <binding name="CallerBeanImplPortBinding" type="tns:CallerService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="doSomething">
            <soap:operation soapAction=""/>
            <wsp:PolicyReference URI="#fa2b7148-7ff9-4866-b2af-5124a91d4f9e"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="CallerService2">
        <port name="CallerBeanImplPort" binding="tns:CallerBeanImplPortBinding">
            <soap:address location="http://localhost:9082/caller/CallerService2"/>
        </port>
    </service>
    <wsp:Policy wsu:Id="fa2b7148-7ff9-4866-b2af-5124a91d4f9e"><wsp:ExactlyOne><wsp:All><wspns0:ATAssertion xmlns:wspns0="http://schemas.xmlsoap.org/ws/2004/10/wsat" wsp:Optional="true"/></wsp:All><wsp:All><ns2:ATAssertion xmlns:ns2="http://docs.oasis-open.org/ws-tx/wsat/2006/06" wsp:Optional="true"/></wsp:All></wsp:ExactlyOne><wsp:ExactlyOne><wsp:All><ns4:BAAtomicOutcomeAssertion xmlns:ns4="http://schemas.xmlsoap.org/ws/2004/10/wsba" wsp:Optional="true"/></wsp:All><wsp:All><ns3:BAAtomicOutcomeAssertion xmlns:ns3="http://docs.oasis-open.org/ws-tx/wsba/2006/06" wsp:Optional="true"/></wsp:All></wsp:ExactlyOne></wsp:Policy>
</definitions>
