<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://api.ws.transactions.lkp.lanit.ru/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http"
    xmlns:wsat11="http://docs.oasis-open.org/ws-tx/wsat/2006/06"
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" name="CallerService"
    targetNamespace="http://api.ws.transactions.lkp.lanit.ru/">

    <wsp:Policy xmlns:wsp="http://www.w3.org/ns/ws-policy" wsu:Id="5093fdc2-0adc-4db7-839a-ac707aea7928">
        <wsp:ExactlyOne>
            <wsp:All>
                <wspns0:ATAssertion xmlns:wspns0="http://schemas.xmlsoap.org/ws/2004/10/wsat"
                    wsp:Optional="true" />
            </wsp:All>
            <wsp:All>
                <ns2:ATAssertion xmlns:ns2="http://docs.oasis-open.org/ws-tx/wsat/2006/06"
                    wsp:Optional="true" />
            </wsp:All>
        </wsp:ExactlyOne>
        <wsp:ExactlyOne>
            <wsp:All>
                <ns4:BAAtomicOutcomeAssertion
                    xmlns:ns4="http://schemas.xmlsoap.org/ws/2004/10/wsba" wsp:Optional="true" />
            </wsp:All>
            <wsp:All>
                <ns3:BAAtomicOutcomeAssertion
                    xmlns:ns3="http://docs.oasis-open.org/ws-tx/wsba/2006/06" wsp:Optional="true" />
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>

    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:tns="http://api.ws.transactions.lkp.lanit.ru/" elementFormDefault="unqualified"
            targetNamespace="http://api.ws.transactions.lkp.lanit.ru/" version="1.0">

            <xs:element name="doSomething" type="tns:doSomething" />

            <xs:element name="doSomethingResponse" type="tns:doSomethingResponse" />

            <xs:complexType name="doSomething">
                <xs:sequence>
                    <xs:element minOccurs="0" name="arg0" type="xs:string" />
                </xs:sequence>
            </xs:complexType>

            <xs:complexType name="doSomethingResponse">
                <xs:sequence>
                    <xs:element minOccurs="0" name="return" type="xs:string" />
                </xs:sequence>
            </xs:complexType>

        </xs:schema>
    </wsdl:types>
    <wsdl:message name="doSomethingResponse">
        <wsdl:part element="tns:doSomethingResponse" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="doSomething">
        <wsdl:part element="tns:doSomething" name="parameters">
        </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="CallerService">
        <wsdl:operation name="doSomething">
            <wsdl:input message="tns:doSomething" name="doSomething">
            </wsdl:input>
            <wsdl:output message="tns:doSomethingResponse" name="doSomethingResponse">
            </wsdl:output>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CallerServiceSoapBinding" type="tns:CallerService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="doSomething">
            <soap:operation soapAction="" style="document" />
            <wsp:PolicyReference xmlns:wsp="http://www.w3.org/ns/ws-policy" URI="#5093fdc2-0adc-4db7-839a-ac707aea7928"/>
            <wsdl:input name="doSomething">
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output name="doSomethingResponse">
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="CallerService">
        <wsdl:port binding="tns:CallerServiceSoapBinding" name="CallerServiceImplPort">
            <soap:address location="http://localhost:9082/caller/CallerService" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>