version: '3'

services:
   #
   # WildFly координатора транзакций
   #
  coordinator_backend:
   build: ./coordinator
   image: lkp_transactions_coordinator
   hostname: coordinator_backend
   ports:
     - "11080:8080"
     - "11990:9990"
   networks:
     - mynetwork

   #
   # Прокся для координатора - она логирует все обращения к нему (в проде не нужна)
   #
  coordinator:
   build: ./logproxy
   image: lkp_transactions_logproxy
   hostname: coordinator
   ports:
     - "10080:8080"
     - "10990:9990"
   networks:
     - mynetwork
   depends_on:
      - coordinator_backend

   #
   # Вызываемый сервер 1
   #
  callee_master:
   build: ./callee
   image: lkp_transactions_callee
   hostname: callee_master
   ports:
     - "10081:8080"
     - "10991:9990"
     - "8788:8787/tcp"
   depends_on:
      - coordinator
      - db
   volumes:
     - ./callee/deployments_master:/opt/jboss/wildfly/standalone/deployments:rw
   networks:
     - mynetwork

   #
   # Вызываемый сервер 2
   #
  callee_slave:
   build: ./callee
   image: lkp_transactions_callee
   hostname: callee_slave
   ports:
     - "10082:8080"
     - "10992:9990"
     - "8789:8787/tcp"
   depends_on:
      - coordinator
      - db
   volumes:
     - ./callee/deployments_slave:/opt/jboss/wildfly/standalone/deployments:rw
   networks:
     - mynetwork

   #
   # Балансировщик нагрузки
   #
  callee:
   build: ./nginx
   image: lkp_transactions_nginx
   hostname: callee
   ports:
     - "10083:8080"
   depends_on:
      - callee_master
      - callee_slave
   networks:
     - mynetwork

   #
   # Вызывающий сервер
   #
  caller:
   build: ./caller
   image: lkp_transactions_caller
   hostname: caller
   ports:
     - "10084:8080"
     - "10994:9990"
     - "8787:8787/tcp"
   volumes:
     - ./caller/deployments:/opt/jboss/wildfly/standalone/deployments:rw
   depends_on:
      - coordinator
      - callee
      - db
   networks:
     - mynetwork

   #
   # Oracle
   #
  db:
   build: ./db
   image: lkp_transactions_db
   hostname: caller
   ports:
     - "11521:1521/tcp"
   networks:
     - mynetwork

networks:
  mynetwork:
    driver: bridge