version: '3'

services:
  callee_master:
   build: .
   image: lkp_transactions_callee
   hostname: callee_master
   ports:
     - "8081:8080"
     - "9991:9990"
#     - "8787:8787/tcp"
   volumes:
     - ./callee/deployments_master:/opt/jboss/wildfly/standalone/deployments:rw
   networks:
     - mynetwork

  callee_slave:
   build: .
   image: lkp_transactions_callee
   hostname: callee_slave
   ports:
     - "8082:8080"
     - "9992:9990"
#     - "8787:8787/tcp"
   volumes:
     - ./callee/deployments_slave:/opt/jboss/wildfly/standalone/deployments:rw
   networks:
     - mynetwork

  callee:
   build: .
   image: lkp_transactions_nginx
   hostname: callee
   ports:
     - "8083:8080"
   depends_on:
      - callee_master
      - callee_slave
   networks:
     - mynetwork

  caller:
   build: .
   image: lkp_transactions_caller
   hostname: caller
   ports:
     - "8084:8080"
     - "9994:9990"
#     - "8787:8787/tcp"
   volumes:
     - ./caller/deployments:/opt/jboss/wildfly/standalone/deployments:rw
   depends_on:
      - callee
   networks:
     - mynetwork

networks:
  mynetwork:
    driver: bridge