//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ru.lanit.lkp.transactions;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

@WebServiceClient(name = "CallerService", targetNamespace = "http://api.ws.transactions.lkp.lanit.ru/", wsdlLocation = "/wsdl/CallerService.wsdl")
public class CallerService_Service
    extends Service
{

    private final static URL CALLERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ru.lanit.lkp.transactions.CallerService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ru.lanit.lkp.transactions.CallerService_Service.class.getResource(".");
            url = new URL(baseUrl, "/wsdl/CallerService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '/wsdl/CallerService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CALLERSERVICE_WSDL_LOCATION = url;
    }

    public CallerService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CallerService_Service() {
        super(CALLERSERVICE_WSDL_LOCATION, new QName("http://api.ws.transactions.lkp.lanit.ru/", "CallerService"));
    }

    /**
     * 
     * @return
     *     returns CallerService
     */
    @WebEndpoint(name = "CallerServiceImplPort")
    public CallerService getCallerServiceImplPort() {
        return super.getPort(new QName("http://api.ws.transactions.lkp.lanit.ru/", "CallerServiceImplPort"), CallerService.class);
    }

}
