CREATE USER ZAKUPKI_DEV identified by ZAKUPKI_DEV DEFAULT TABLESPACE USERS;
GRANT RESOURCE, CONNECT TO ZAKUPKI_DEV;

CREATE TABLE "ZAKUPKI_DEV"."OPERATION_JOURNAL" 
(
    "OP_JOURNAL_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"ORDER_ID" NUMBER(20,0), 
	"USER_UID" VARCHAR2(100 CHAR), 
	"EVENT_TYPE" VARCHAR2(10 BYTE), 
	"TMSTMP" TIMESTAMP (6), 
	"EVENT_NAME" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	"OBJECT_TYPE" VARCHAR2(5 BYTE), 
	"USER_FIO" VARCHAR2(200 BYTE), 
	"NOTIFICATION_ID" NUMBER(20,0), 
	"MODIFICATION_TYPE" VARCHAR2(1 BYTE), 
	"IS_PARTIAL" NUMBER(1,0), 
	"IP" VARCHAR2(50 BYTE), 
	"EVENT" VARCHAR2(100 BYTE), 
	"EVENT_CLASS" VARCHAR2(50 BYTE), 
	"LOCAL_TMSTMP" TIMESTAMP (6), 
	"OBJECT_KEY" VARCHAR2(200 BYTE), 
	"SHORT_MESSAGE" VARCHAR2(2000 BYTE), 
	"AGREGATE_OBJECT_ID" NUMBER(20,0), 
	"USER_ID" NUMBER(20,0), 
	"MESSAGE" VARCHAR2(4000 BYTE), 
	"REFERENCE_OBJECT_DESTINATION" VARCHAR2(100 BYTE), 
	 CONSTRAINT "PK_OP_JOURNAL" PRIMARY KEY ("OP_JOURNAL_ID")
);

GRANT SELECT, INSERT, UPDATE, DELETE ON ZAKUPKI_DEV.OPERATION_JOURNAL TO ZAKUPKI_DEV;

CREATE SEQUENCE ZAKUPKI_DEV.SEQ_OPERATION_JOURNAL;

GRANT SELECT ON ZAKUPKI_DEV.SEQ_OPERATION_JOURNAL TO ZAKUPKI_DEV;