//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package ru.lanit.lkp.transactions;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

@WebServiceClient(name = "CalleeService", targetNamespace = "http://api.ws.transactions.lkp.lanit.ru/", wsdlLocation = "/wsdl/CalleeService.wsdl")
public class CalleeService_Service
    extends Service
{

    private final static URL CALLEESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ru.lanit.lkp.transactions.CalleeService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ru.lanit.lkp.transactions.CalleeService_Service.class.getResource(".");
            url = new URL(baseUrl, "/wsdl/CalleeService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '/wsdl/CalleeService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CALLEESERVICE_WSDL_LOCATION = url;
    }

    public CalleeService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalleeService_Service() {
        super(CALLEESERVICE_WSDL_LOCATION, new QName("http://api.ws.transactions.lkp.lanit.ru/", "CalleeService"));
    }

    /**
     * 
     * @return
     *     returns CalleeService
     */
    @WebEndpoint(name = "CalleeServiceImplPort")
    public CalleeService getCalleeServiceImplPort() {
        return super.getPort(new QName("http://api.ws.transactions.lkp.lanit.ru/", "CalleeServiceImplPort"), CalleeService.class);
    }

}
